#!/usr/bin/env python3
# Compiled from arc_agi3_option_d_offline_kaggle.ipynb
# Adapted for local (non-Kaggle) execution.
#
# Usage:
#   OPENAI_API_KEY=<key> python option_d_offline.py
#
# The script runs completely offline — no calls to three.arcprize.org.
# It discovers game environments from environment_files/ (if any) and
# runs ReasoningAgent + WorldModelAgent, printing the final two scores.

# ── Cell 2 — dependencies ──────────────────────────────────────────────────
import subprocess
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent

# ── Cell 4 — secrets / env setup ──────────────────────────────────────────
import os

def get_secret(name: str, required: bool = False) -> str:
    """Read a secret from env var or .env file."""
    val = os.environ.get(name, "")
    if not val:
        # Try reading from .env manually
        env_file = REPO_DIR / ".env"
        if env_file.exists():
            for line in env_file.read_text().splitlines():
                line = line.strip()
                if line.startswith(f"{name}="):
                    val = line.split("=", 1)[1].strip()
                    break
    if required and not val:
        raise RuntimeError(
            f"Secret '{name}' not found. "
            f"Set it as an environment variable or add it to .env."
        )
    return val

openai_api_key = get_secret("OPENAI_API_KEY", required=True)
agentops_key   = get_secret("AGENTOPS_API_KEY")

ENV_DIR = REPO_DIR / "environment_files"
ENV_DIR.mkdir(parents=True, exist_ok=True)

env_text = f"""# Auto-generated by option_d_offline.py
DEBUG=False
RECORDINGS_DIR=recordings
OPERATION_MODE=offline
ENVIRONMENTS_DIR=environment_files
WDM_LOG=0
OPENAI_API_KEY={openai_api_key}
ARC_API_KEY=
AGENTOPS_API_KEY={agentops_key}
"""

(REPO_DIR / ".env").write_text(env_text)

os.environ["OPENAI_API_KEY"]   = openai_api_key
os.environ["OPERATION_MODE"]   = "offline"
os.environ["ENVIRONMENTS_DIR"] = str(ENV_DIR)
os.environ["PYTHONPATH"]       = str(REPO_DIR)

print("OPENAI_API_KEY  set:", bool(openai_api_key))
print("OPERATION_MODE  :", os.environ["OPERATION_MODE"])
print(".env written to :", REPO_DIR / ".env")

# ── Cell 6 — repo already present locally ─────────────────────────────────
REPO_CLONE = REPO_DIR
os.chdir(REPO_CLONE)
print("Working directory:", Path.cwd())

# ── Cell 8 — parse JSON environments ──────────────────────────────────────
import json
import shutil

# Search for metadata.json files under environment_files/
SEARCH_ROOTS = [REPO_CLONE / "environment_files"]

installed: list[str] = []
skipped:   list[str] = []

for root in SEARCH_ROOTS:
    if not root.exists():
        continue
    for meta_file in sorted(root.rglob("metadata.json")):
        try:
            meta_file.relative_to(ENV_DIR)
        except ValueError:
            pass

        try:
            meta = json.loads(meta_file.read_text(encoding="utf-8"))
            game_id = meta.get("game_id", "").strip()
            if not game_id:
                skipped.append(str(meta_file))
                continue

            dst_dir = ENV_DIR / game_id
            if dst_dir.exists():
                if game_id not in installed:
                    installed.append(game_id)
                continue

            dst_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(meta_file, dst_dir / "metadata.json")

            py_files = list(meta_file.parent.glob("*.py"))
            for py_file in py_files:
                shutil.copy2(py_file, dst_dir / py_file.name)

            installed.append(game_id)
            py_names = [p.name for p in py_files]
            print(f"  ✓ {game_id:20s} ← {meta_file.parent.name}/  (py: {py_names})")

        except Exception as exc:
            skipped.append(f"{meta_file} ({exc})")

print()
print(f"Environments installed : {len(installed)}  → {installed}")
if skipped:
    print(f"Skipped (no game_id)   : {len(skipped)}")

if not installed:
    print()
    print("╔══════════════════════════════════════════════════════╗")
    print("║  NOTE: No environments found in environment_files/. ║")
    print("║  Both agents will run and return levels_completed=0 ║")
    print("║  (the two-score guarantee is still met).            ║")
    print("║  Add game environments to environment_files/ for    ║")
    print("║  real scores.                                       ║")
    print("╚══════════════════════════════════════════════════════╝")

GAMES_AVAILABLE = installed[:]

# ── Cell 10 — PMLL memory shim ────────────────────────────────────────────
import importlib.util
import time

PMLL_AVAILABLE = importlib.util.find_spec("pmll_memory_mcp") is not None


class _PMLLShim:
    """Thin in-process shim used when pmll_memory_mcp is absent."""

    def __init__(self) -> None:
        self._store: dict = {}
        self._graph: list = []
        print("  [shim] pmll_memory_mcp not found — using in-process shim")

    def init(self, session_id: str, silo_size: int = 256) -> dict:
        self._store.setdefault(session_id, {})
        return {"status": "ok", "session_id": session_id, "silo_size": silo_size}

    def set(self, session_id: str, key: str, value: object) -> dict:
        self._store.setdefault(session_id, {})[key] = value
        return {"status": "stored", "key": key}

    def peek(self, session_id: str, key: str) -> object:
        return self._store.get(session_id, {}).get(key)

    def upsert_memory_node(
        self,
        session_id: str,
        node_type: str,
        label: str,
        content: str,
        metadata: dict | None = None,
    ) -> dict:
        for node in self._graph:
            if node["label"] == label:
                node.update({"type": node_type, "content": content,
                              "metadata": metadata or {},
                              "updated_at": time.time()})
                return {"status": "updated", "label": label}
        self._graph.append({"type": node_type, "label": label,
                             "content": content, "metadata": metadata or {},
                             "created_at": time.time()})
        return {"status": "created", "label": label}

    def search_memory_graph(self, session_id: str, query: str, top_k: int = 5) -> dict:
        hits = [n for n in self._graph if query.lower() in n["content"].lower()]
        return {"results": hits[:top_k]}

    def dump_graph(self, session_id: str) -> list:
        return list(self._graph)

    def flush(self, session_id: str) -> dict:
        self._store.pop(session_id, None)
        return {"status": "flushed"}


if PMLL_AVAILABLE:
    try:
        import pmll_memory_mcp as pmll_mod
        pmll = pmll_mod
        print("  [pmll] using pmll_memory_mcp package")
    except Exception:
        pmll = _PMLLShim()
else:
    pmll = _PMLLShim()

SESSION_ID = "arc3_option_d_offline"
pmll.init(SESSION_ID, silo_size=512)

pmll.set(SESSION_ID, "agent_identity",  "stochastic_goose")
pmll.set(SESSION_ID, "run_mode",        "offline_option_d")
pmll.set(SESSION_ID, "games_available", json.dumps(GAMES_AVAILABLE))
pmll.upsert_memory_node(
    SESSION_ID, "identity", "stochastic_goose",
    "Baseline stochastic goose identity seeded at Option D start. "
    "Will be superseded by world_model_agent after WorldModelAgent run.",
)

print(f"PMLL session '{SESSION_ID}' initialised.")
print("Identity:", pmll.peek(SESSION_ID, "agent_identity"))

# ── Cell 12 — run_agent helper ────────────────────────────────────────────
import re


def run_agent(
    agent_name: str,
    tags: str,
    game: str | None = None,
    timeout: int = 1800,
    pmll_session: str = SESSION_ID,
) -> dict:
    """Run *agent_name* via main.py and ALWAYS return a scored result dict."""
    result: dict = {
        "agent":            agent_name,
        "tags":             tags,
        "game":             game or "ALL",
        "levels_completed": 0,
        "win_levels":       0,
        "elapsed_s":        0.0,
        "returncode":       -1,
        "error":            None,
        "log_tail":         "",
    }

    try:
        cmd = [
            sys.executable,
            str(REPO_CLONE / "main.py"),
            f"--agent={agent_name}",
            f"--tags={tags}",
        ]
        if game:
            cmd.append(f"--game={game}")

        env = os.environ.copy()
        env["PYTHONPATH"]       = str(REPO_CLONE)
        env["OPERATION_MODE"]   = "offline"
        env["ENVIRONMENTS_DIR"] = str(ENV_DIR)
        env["DOTENV_PATH"]      = str(REPO_CLONE / ".env")
        env["TESTING"]          = "False"

        print(f"\n>>> Starting {agent_name!r} (tags={tags!r}, game={game or 'ALL'})")
        t0 = time.time()

        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            env=env,
        )

        result["elapsed_s"]  = round(time.time() - t0, 1)
        result["returncode"] = proc.returncode

        full_log = proc.stdout + proc.stderr
        result["log_tail"] = full_log[-4000:]

        # Parse FINAL SCORECARD REPORT JSON block
        json_match = re.search(
            r"FINAL SCORECARD REPORT.*?(\{.*?\})",
            full_log, re.DOTALL,
        )
        if json_match:
            try:
                summary = json.loads(json_match.group(1))
                result["levels_completed"] = int(summary.get("levels_completed", 0))
                result["win_levels"]       = int(summary.get("win_levels", 0))
            except (json.JSONDecodeError, ValueError):
                pass

        # Fallback: scan log lines for numeric level completions
        for line in full_log.splitlines():
            m = re.search(r'"levels_completed"\s*:\s*(\d+)', line)
            if m:
                result["levels_completed"] = max(
                    result["levels_completed"], int(m.group(1))
                )
            m = re.search(r'"win_levels"\s*:\s*(\d+)', line)
            if m:
                result["win_levels"] = max(result["win_levels"], int(m.group(1)))

        for line in full_log.splitlines():
            m = re.search(r'levels completed (\d+)', line, re.IGNORECASE)
            if m:
                result["levels_completed"] = max(
                    result["levels_completed"], int(m.group(1))
                )

    except subprocess.TimeoutExpired:
        result["error"] = f"Timeout after {timeout}s"
    except Exception as exc:
        result["error"] = str(exc)

    # PMLL: upsert per-agent memory node (emergence step)
    try:
        snapshot = json.dumps({
            "agent":            agent_name,
            "game":             result["game"],
            "levels_completed": result["levels_completed"],
            "win_levels":       result["win_levels"],
            "elapsed_s":        result["elapsed_s"],
            "error":            result["error"],
        })
        pmll.upsert_memory_node(
            pmll_session, "run_result", f"optionD_{agent_name}", snapshot
        )
        if agent_name == "worldmodelagent":
            pmll.set(pmll_session, "agent_identity", "world_model_agent")
            pmll.upsert_memory_node(
                pmll_session, "identity", "world_model_agent",
                f"Emerged from stochastic_goose after WorldModelAgent run. "
                f"levels_completed={result['levels_completed']}",
            )
    except Exception:
        pass

    status = "OK" if result["error"] is None else f"ERR({result['error'][:60]})"
    print(
        f"    {agent_name}: levels_completed={result['levels_completed']}, "
        f"win_levels={result['win_levels']}, "
        f"elapsed={result['elapsed_s']}s, status={status}"
    )
    return result


print("run_agent helper defined.")

# ── Cell 14 — run ReasoningAgent (baseline / Stochastic Goose) ────────────
print("Pre-run PMLL identity:", pmll.peek(SESSION_ID, "agent_identity"))

result_baseline = run_agent(
    agent_name="reasoningagent",
    tags="baseline,optionD,offline,stochastic_goose",
)

print(json.dumps(
    {k: v for k, v in result_baseline.items() if k != "log_tail"},
    indent=2,
))

# ── Cell 16 — run WorldModelAgent (emergence) ─────────────────────────────
result_worldmodel = run_agent(
    agent_name="worldmodelagent",
    tags="worldmodel,optionD,offline,emergence",
)

print(json.dumps(
    {k: v for k, v in result_worldmodel.items() if k != "log_tail"},
    indent=2,
))

print("\nPost-run PMLL identity:", pmll.peek(SESSION_ID, "agent_identity"))

# ── Cell 18 — OPTION D FINAL SCORES ──────────────────────────────────────
import pandas as pd

lc_baseline   = int(result_baseline.get("levels_completed", 0))
lc_worldmodel = int(result_worldmodel.get("levels_completed", 0))
wl_baseline   = int(result_baseline.get("win_levels",       0))
wl_worldmodel = int(result_worldmodel.get("win_levels",     0))

rows = [
    {
        "agent":            "ReasoningAgent  (baseline)",
        "mode":             "offline / Option D",
        "levels_completed": lc_baseline,
        "win_levels":       wl_baseline,
        "elapsed_s":        result_baseline["elapsed_s"],
        "error":            result_baseline["error"] or "—",
    },
    {
        "agent":            "WorldModelAgent (world model)",
        "mode":             "offline / Option D",
        "levels_completed": lc_worldmodel,
        "win_levels":       wl_worldmodel,
        "elapsed_s":        result_worldmodel["elapsed_s"],
        "error":            result_worldmodel["error"] or "—",
    },
]
df = pd.DataFrame(rows).set_index("agent")

print()
print("=" * 62)
print("  OPTION D — FINAL SCORES  (offline, behind firewall)")
print("=" * 62)
print(df.to_string())
print("=" * 62)
print()
print(f"  Baseline   (ReasoningAgent):   levels_completed = {lc_baseline:>4}  |  win_levels = {wl_baseline}")
print(f"  WorldModel (WorldModelAgent):  levels_completed = {lc_worldmodel:>4}  |  win_levels = {wl_worldmodel}")
print("=" * 62)

if result_baseline["error"]:
    print(f"  [WARN] Baseline error  : {result_baseline['error']}")
if result_worldmodel["error"]:
    print(f"  [WARN] WorldModel error: {result_worldmodel['error']}")
if not GAMES_AVAILABLE:
    print("  [WARN] No game environments found in environment_files/.")
    print("         Populate it with game metadata.json + .py files for real scores.")

# ── Cell 20 — PMLL memory graph after emergence ───────────────────────────
print("=== Memory graph after Option D emergence ===")
try:
    graph = pmll.dump_graph(SESSION_ID) if hasattr(pmll, "dump_graph") else []
    for node in graph:
        print(f"  [{node.get('type', '?')}] {node.get('label', '?')}: "
              f"{str(node.get('content', ''))[:120]}")
except Exception as exc:
    print(f"  (PMLL graph unavailable: {exc})")

print()
print("=== Search: 'optionD' ===")
try:
    hits = pmll.search_memory_graph(SESSION_ID, "optionD")
    for h in hits.get("results", []):
        print(f"  {h.get('label', '?')}: {str(h.get('content', ''))[:120]}")
except Exception:
    pass

print()
print("=== Final agent identity ===")
print(" ", pmll.peek(SESSION_ID, "agent_identity"))

# ── Cell 22 — save results and flush PMLL session ─────────────────────────
from datetime import datetime

timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
out_dir   = REPO_CLONE / "option_d_output"
out_dir.mkdir(parents=True, exist_ok=True)
out_path  = out_dir / f"option_d_results_{timestamp}.json"

try:
    memory_graph = pmll.dump_graph(SESSION_ID) if hasattr(pmll, "dump_graph") else []
except Exception:
    memory_graph = []

results_payload = {
    "timestamp":          timestamp,
    "option":             "D_offline",
    "pmll_session_id":    SESSION_ID,
    "games_available":    GAMES_AVAILABLE,
    "final_scores": {
        "baseline_levels_completed":    lc_baseline,
        "baseline_win_levels":          wl_baseline,
        "worldmodel_levels_completed":  lc_worldmodel,
        "worldmodel_win_levels":        wl_worldmodel,
    },
    "memory_graph": memory_graph,
    "runs": [
        {k: v for k, v in result_baseline.items()   if k != "log_tail"},
        {k: v for k, v in result_worldmodel.items() if k != "log_tail"},
    ],
}

out_path.write_text(json.dumps(results_payload, indent=2, default=str))
print(f"Results saved → {out_path}")

for r in [result_baseline, result_worldmodel]:
    log_path = out_dir / f"{r['agent']}_optionD_{timestamp}.log"
    log_path.write_text(r.get("log_tail", ""))
    print(f"Log  saved  → {log_path}")

try:
    pmll.flush(SESSION_ID)
    print("PMLL silo flushed.")
except Exception:
    pass

print()
print("Option D complete.")
print(f"  Baseline   levels_completed : {lc_baseline}")
print(f"  WorldModel levels_completed : {lc_worldmodel}")
